version: '3.8'

services:
  calculator:
    build:
      context: .
    image: calculator
    ports:
      - "8082:80"
    volumes:
      - .:/usr/share/nginx/html
    container_name: calculator
    restart: always
  
